server.port: 7003
server.error.include-message: always

# Strongly recommend to set this property to "none" in a production environment!
spring.jpa.hibernate.ddl-auto: update
spring.datasource:
  url: jdbc:mysql://localhost:3306/identity-db?createDatabaseIfNotExist=true&useSSL=false
  username: root
  password: i8tu6uZD_123

spring.datasource.hikari.initializationFailTimeout: 60000

logging:
  level:
    root: INFO
    com.eaa: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

allowed.origins: /identity/welcome, /identity/register, /identity/authenticate, /identity/verifyRegistration, /identity/forgot-password/**, /identity/reset-password
---
spring.config.activate.on-profile: docker

server.port: 8080

spring.datasource:
  url: jdbc:mysql://mysql/identity-db
  username: user
  password: pwd