version: '3.8'
services:
  mysql:
    image: mysql:8.0.32
    mem_limit: 512m
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=identity-db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
    volumes:
      - mysql_data:/var/lib/mysql      
    healthcheck:
      test: "/usr/bin/mysql --user=user --password=pwd --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 2s
      retries: 60    
       
  identity:
    build: identity-service
    image: identity-service:v1.0
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data:        