spring:
  datasource:
    url: jdbc:mysql://localhost:3306/full-stack-ecommerce?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        
     
    
#allowed:
#  origins: https://localhost:4200    
                
## Stripe Config ##
stripe.key.secret: sk_test_51KeUeEGtKYzle2NaumWyt2KjQefHn7ppUvChDYQj818Fvf0mnsrdTHC712F53xJ7KueGVI4yw2939YT218uPhOHI00i31NlPFc


#####
#
# HTTPS configuration
#
#####

# Server web port
server:
  port: 8080
  ssl:
    enabled: true
    key-alias: luv2code
    key-store: classpath:luv2code-keystore.p12
    key-store-password: secret
    key-store-type: PKCS12
  servlet:
    context-path: /api   


##
## In the terminal window, run this command to generate the key and certificate. 
## This is one long command, copy/paste in its entirety.
##
##
## keytool -genkeypair -alias luv2code -keystore src/main/resources/luv2code-keystore.p12 -keypass secret -storeType PKCS12 
## -storepass secret -keyalg RSA -keysize 2048 -validity 365 -dname "C=US, ST=Pennsylvania, L=Philadelphia, O=luv2code, OU=Training Backend, CN=localhost" -ext "SAN=dns:localhost"

    
    